name: Continuous Integration (CI)

# O pipeline será executado a cada push para branches e pull requests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job para executar os testes
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Defina a versão do Python que sua aplicação utiliza

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar as dependências do projeto

    - name: Run tests
      run: |
        # Executar os testes unitários com pytest
        pytest --maxfail=1 --disable-warnings -q
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Exemplo de variáveis de ambiente para banco de dados

    - name: Check code formatting with black
      run: |
        black --check .  # Verifica se o código segue o padrão do black

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .  # Verifica erros de estilo e qualidade de código

  # Job opcional para realizar a análise de segurança do código
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Safety for security vulnerabilities
      run: |
        pip install safety
        safety check  # Executa a verificação de vulnerabilidades conhecidas

  # Job opcional para realizar o build e deploy (caso necessário)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # O job de deploy só rodará se o job de teste passar com sucesso
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        # Comandos de deploy para a AWS ou outro provedor de sua escolha
        echo "Deploying the application..."  # Exemplo de comando de deploy (personalizar conforme sua necessidade)
